var poems = [
    "I think that I shall never see <br/>A poem lovely as a tree.<br/><br/>A tree whose hungry mouth is prest <br/> Against the earths sweet flowing breast<br/><br/>A tree that looks at God all day<br/>And lifts her leafy arms to pray<br/><br/>A tree that may in summer wear<br/>A nest of robins in her hair<br/><br/>Upon whose bosom snow has lain<br/> Who intimately lives with rain.<br/><br/>Poems are made by fools like me,<br/>But only God can make a tree.",
    
    "Take this kiss upon the brow!<br/>And, in parting from you now,<br/>Thus much let me avow-<br/>You are not wrong, who deem<br/>That my days have been a dream;<br/>Yet if hope has flown away<br/>In a night, or in a day,<br/>In a vision, or in none,<br/>Is it therefore the less gone?<br/>All that we see or seem<br/>Is but a dream within a dream.<br/><br/>I stand amid the roar<br/>Of a surf-tormented shore,<br/>And I hold within my hand<br/>Grains of the golden sand-<br/>How few! yet how they creep<br/>Through my fingers to the deep,<br/>While I weep - while I weep!<br/>O God! can I not grasp<br/>Them with a tighter clasp?<br/>O God! can I not save<br/>One from the pitiless wave?<br/>Is all that we see or seem<br/>But a dream within a dream?",
    
    "Two roads diverged in a yellow wood,<br/>And sorry I could not travel both<br/>And be one traveler, long I stood<br/>And looked down one as far as I could<br/>To where it bent in the undergrowth;<br/><br/>Then took the other, as just as fair,<br/>And having perhaps the better claim,<br/>Because it was grassy and wanted wear;<br/>Though as for that the passing there<br/>Had worn them really about the same,<br/><br/>And both that morning equally lay<br/>In leaves no step had trodden black.<br/>Oh, I kept the first for another day!<br/>Yet knowing how way leads on to way,<br/>I doubted if I should ever come back.<br/><br/>I shall be telling this with a sigh<br/>Somewhere ages and ages hence:<br/>Two roads diverged in a wood, and I—<br/>I took the one less traveled by,<br/>And that has made all the difference.",
    
    "She walks in beauty, like the night<br/>Of cloudless climes and starry skies;<br/>And all that's best of dark and bright<br/>Meet in her aspect and her eyes:<br/>Thus mellowed to that tender light<br/>Which heaven to gaudy day denies.<br/><br/>One shade the more, one ray the less,<br/>Had half impaired the nameless grace<br/>Which waves in every raven tress,<br/>Or softly lightens o'er her face;<br/>Where thoughts serenely sweet express<br/>How pure, how dear their dwelling-place.<br/><br/>And on that cheek, and o'er that brow, <br/>So soft, so calm, yet eloquent,<br/>The smiles that win, the tints that glow,<br/>But tell of days in goodness spent,<br/>A mind at peace with all below,<br/>A heart whose love is innocent.",
    
    "No coward soul is mine,<br/>No trembler in the world's storm-troubled sphere:<br/>I see Heaven's glories shine,<br/>And faith shines equal, arming me from fear.<br/><br/>O God within my breast,<br/>Almighty, ever-present Deity!<br/>Life - that in me has rest,<br/>As I - undying Life - have power in thee!<br/><br/>Vain are the thousand creeds<br/>That move men's hearts: unutterably vain;<br/>Worthless as withered weeds,<br/>Or idlest froth amid the boundless main,<br/><br/>To waken doubt in one<br/>Holding so fast by thine infinity;<br/>So surely anchored on<br/>The steadfast rock of immortality.<br/><br/>With wide-embracing love<br/>Thy spirit animates eternal years,<br/>Pervades and broods above,<br/>Changes, sustains, dissolves, creates, and rears.<br/><br/>Though earth and man were gone,<br/>And suns and universes ceased to be,<br/>And thou were left alone,<br/>Every existence would exist in thee.<br/><br/>There is not room for Death,<br/>Nor atom that his might could render void:<br/>Thou - thou art Being and Breath,<br/>And what thou art may never be destroyed.",
    
    "I died for Beauty – but was scarce<br/>Adjusted in the Tomb<br/>When One who died for Truth, was lain<br/>In an adjoining Room –<br/><br/>He questioned softly ‘Why I failed’?<br/>‘For Beauty’, I replied –<br/>‘And I – for Truth – Themself are One –<br/>We Bretheren, are’, He said –<br/><br/>And so, as Kinsmen, met a Night –<br/>We talked between the Rooms –<br/>Until the Moss had reached our lips –<br/>And covered up – our names –",
    
    "What is this life if, full of care,<br/>We have no time to stand and stare.<br/><br/>No time to stand beneath the boughs<br/>And stare as long as sheep or cows.<br/><br/>No time to see, when woods we pass,<br/>Where squirrels hide their nuts in grass.<br/><br/>No time to see, in broad daylight,<br/>Streams full of stars, like skies at night.<br/><br/>No time to turn at Beauty's glance,<br/>And watch her feet, how they can dance.<br/><br/>No time to wait till her mouth can<br/>Enrich that smile her eyes began.<br/><br/>A poor life this is if, full of care,<br/>We have no time to stand and stare.",
    
    " If it is not my portion to meet thee in this life<br/>then let me ever feel that I have missed thy sight <br/>---let me not forget for a moment, <br/>let me carry the pangs of this sorrow in my dreams <br/>and in my wakeful hours.<br/><br/>As my days pass in the crowded market of this world <br/>and my hands grow full with the daily profits, <br/>let me ever feel that I have gained nothing <br/>---let me not forget for a moment, <br/>let me carry the pangs of this sorrow in my dreams <br/>and in my wakeful hours.<br/><br/>When I sit by the roadside, tired and panting, <br/>when I spread my bed low in the dust, <br/>let me ever feel that the long journey is still before me <br/>---let me not forget a moment, <br/>let me carry the pangs of this sorrow in my dreams <br/>and in my wakeful hours.<br/><br/>When my rooms have been decked out and the flutes sound <br/>and the laughter there is loud, <br/>let me ever feel that I have not invited thee to my house <br/>--let me not forget for a moment, <br/>let me carry the pangs of this sorrow in my dreams <br/>and in my wakeful hours"
]